### SUN ###
- id: sun_below_horizon
  alias: Sun Below Horizon
  trigger:
  - event: sunset
    platform: sun
    offset: -00:10:00
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.duarte
      state: home
    - condition: state
      entity_id: device_tracker.silvia
      state: home
  action:
  - service: script.sun_below
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.duarte
      message: >
        Sun Below Horizon
- id: above_horizon
  alias: Above Horizon
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - service: script.sun_above
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.duarte
      message: >
        Automation based on {{ trigger.event }} was triggered.

### TIME ###
- id: turn_off_lights
  alias: Turn Off Lights
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - data: {}
    service: script.turn_off_lights_living_room
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.duarte
      message: >
        Lights turned off at {{ trigger.now }}

### DEVICE TRACK ###
- id: arrive_home_below_horizon
  alias: Arrive Home Below Horizon
  trigger:
  - entity_id: device_tracker.duarte
    event: enter
    platform: zone
    zone: zone.home
  - entity_id: device_tracker.silvia
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: script.arrive_home
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.duarte
      message: >
        {{ trigger.to_state.name }} {{ trigger.event }} {{ trigger.zone.name }} below horizon.
- id: leave_home_duarte
  alias: Leave Home Duarte
  trigger:
  - entity_id: device_tracker.duarte
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - condition: template
    value_template: >
      {{ not is_state('device_tracker.silvia', 'home') }}
  action:
  - service: script.leave_home
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.duarte
      message: >
        {{ trigger.to_state.name }} {{ trigger.event }} {{ trigger.zone.name }}.
- id: leave_home_silvia
  alias: Leave Home Silvia
  trigger:
  - entity_id: device_tracker.silvia
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - condition: template
    value_template: >
      {{ not is_state('device_tracker.duarte', 'home') }}
  action:
  - service: script.leave_home
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.duarte
      message: >
        {{ trigger.to_state.name }} {{ trigger.event }} {{ trigger.zone.name }}.

### MOTION SENSORS ###
- id: movement_kids_room
  alias: Movement Kids Room
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00029a9d0e
    platform: state
    to: 'on'
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00029a9d0e
    to: 'off'
    for: 00:03:00
  action:
  - service: script.check_kids_room_movement

### HEATING SYSTEM ###
- id: living_room_heating_system
  alias: Living Room Heating System
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: input_boolean.living_room_heating_system
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.temperature_158d0002786e71
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: input_number.living_room_heating_system_temperature
  action:
  - service: script.check_living_room_heating_system

### SYSTEM ###
- id: power_state_on_HA_start-up
  alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/POWER"
        payload: "" 