### SUN ###
- id: sun_below_horizon
  alias: Sun Below Horizon
  trigger:
  - event: sunset
    platform: sun
    offset: -00:30:00
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.s8
      state: home
    - condition: state
      entity_id: device_tracker.hp
      state: home
  action:
  - service: script.turn_on_lights_living_room
    data:
      transition: 1
  - service: script.turn_on_presence_lights
    data: {}
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        Sun Below Horizon
- id: above_horizon
  alias: Above Horizon
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - service: script.turn_off_presence_lights
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        Automation based on {{ trigger.event }} was triggered.

### TIME ###
- id: turn_off_lights
  alias: Turn Off Lights
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - data: {}
    service: script.turn_off_lights_living_room
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        Lights turned off at {{ trigger.now }}

### DEVICE TRACK ###
- id: arrive_home_below_horizon
  alias: Arrive Home Below Horizon
  trigger:
  - entity_id: device_tracker.s8
    event: enter
    platform: zone
    zone: zone.home
  - entity_id: device_tracker.hp
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data: {}
    service: script.arrive_home
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        {{ trigger.to_state.name }} {{ trigger.event }} {{ trigger.zone.name }} below horizon.
- id: leave_home_s8
  alias: Leave Home Duarte
  trigger:
  - entity_id: device_tracker.s8
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - condition: template
    value_template: >
      {{ not is_state('device_tracker.hp', 'home') }}
  action:
  - data: {}
    service: script.leave_home
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        {{ trigger.to_state.name }} {{ trigger.event }} {{ trigger.zone.name }}.
- id: leave_home_hp
  alias: Leave Home Silvia
  trigger:
  - entity_id: device_tracker.hp
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - condition: template
    value_template: >
      {{ not is_state('device_tracker.s8', 'home') }}
  action:
  - data: {}
    service: script.leave_home
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        {{ trigger.to_state.name }} {{ trigger.event }} {{ trigger.zone.name }}.

### MOTION SENSORS ###
- id: movement_kids_room
  alias: Movement Kids Room
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00029a9d0e
    platform: state
    to: 'on'
  condition:
  - below: '15'
    condition: numeric_state
    entity_id: sensor.illumination_158d00029a9d0e
  - after: 09:00:00
    before: '23:00:00'
    condition: time
  action:
  - data:
      entity_id: light.yeelight_color_bulb_2
    service: light.turn_on
- id: no_movement_kids_room
  alias: No Movement Kids Room
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00029a9d0e
    to: 'off'
    for: 00:03:00
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.yeelight_color_bulb_2

### HEATING SYSTEM ###
- id: living_room_heating_system
  alias: Living Room Heating System
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: input_boolean.living_room_heating_system
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.temperature_158d0002786e71
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: input_number.living_room_heating_system_temperature
  action:
  - service: script.check_living_room_heating_system