- alias: Turn On Light when Sun below horizon
  trigger:
  - entity_id: sun.sun
    platform: state
    to: below_horizon
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.syter_galaxys8
        state: home
      - condition: state
        entity_id: device_tracker.shyva_galaxys6
        state: home  
  action:
  - data:
      entity_id: light.sala
    service: light.turn_on

- alias: Turn On Light when arrive home
  trigger:
  - entity_id: device_tracker.syter_galaxys8
    event: enter
    platform: zone
    zone: zone.home
  - entity_id: device_tracker.shyva_galaxys6
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: light.sala
    service: light.turn_on

- alias: Turn off light
  trigger:
  - at: 00:30:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.sala
    service: light.turn_off
