- id: sun_below_horizon
  alias: Sun Below Horizon
  trigger:
  - entity_id: sun.sun
    platform: state
    to: below_horizon
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.s8
      state: home
    - condition: state
      entity_id: device_tracker.s6
      state: home
  action:
  - data: {}
    service: script.turn_on_lights_living_room
  - data: {}
    service: script.turn_on_presence_lights
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        Automation based on {{ trigger.event }} was triggered.
- id: arrive_home_below_horizon
  alias: Arrive Home Below Horizon
  trigger:
  - entity_id: device_tracker.s8
    event: enter
    platform: zone
    zone: zone.home
  - entity_id: device_tracker.s6
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data: {}
    service: script.arrive_home
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        {{ trigger.to_state.name }} {{ trigger.event }} {{ trigger.zone.name }} below horizon.
- id: turn_off_lights
  alias: Turn Off Lights
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - data: {}
    service: script.turn_off_lights_living_room
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        Lights turned off at {{ trigger.now }}
- id: leave_home_s8
  alias: Leave Home Duarte
  trigger:
  - entity_id: device_tracker.s8
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - condition: template
    value_template: >
      {{ not is_state('device_tracker.s6', 'home') }}
  action:
  - data: {}
    service: script.leave_home
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        {{ trigger.to_state.name }} {{ trigger.event }} {{ trigger.zone.name }}.
- id: leave_home_s6
  alias: Leave Home Silvia
  trigger:
  - entity_id: device_tracker.s6
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - condition: template
    value_template: >
      {{ not is_state('device_tracker.s8', 'home') }}
  action:
  - data: {}
    service: script.leave_home
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        {{ trigger.to_state.name }} {{ trigger.event }} {{ trigger.zone.name }}.
- id: above_horizon
  alias: Above Horizon
  trigger:
  - entity_id: sun.sun
    platform: state
    to: above_horizon
  condition: []
  action:
  - service: script.turn_off_presence_lights
  - service: script.notify_zanzito
    data_template:
      entity_id: device_tracker.s8
      message: >
        Automation based on {{ trigger.event }} was triggered.
- id: movement_kids_room
  alias: Movement Kids Room
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00029a9d0e
    platform: state
    to: 'on'
  condition:
  - below: '15'
    condition: numeric_state
    entity_id: sensor.illumination_158d00029a9d0e
  - after: 09:00:00
    before: '23:00:00'
    condition: time
  action:
  - data:
      entity_id: light.yeelight_color_bulb_2
    service: light.turn_on
- id: no_movement_kids_room
  alias: No Movement Kids Room
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00029a9d0e
    to: 'off'
    for: 00:03:00
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.yeelight_color_bulb_2