####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

cloud:
config:

frontend:
  javascript_version: latest

http:
  api_password: !secret api_password
  ip_ban_enabled: true
  login_attempts_threshold: 2
  base_url: hassio.duartebrito.pw

logger:
  default: error

recorder:
history:
logbook:
sun:
map:
hassio:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.1.30:3218/
#    url: http://hassio-config.duartebrito.pw/

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

group: !include groups.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml
media_player: !include media_players.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml
light: !include light.yaml
camera: !include camera.yaml
scene: !include scene.yaml

####################################################
#                                                  #
#                   WEATHER                        #
#                                                  #
####################################################

weather:
  - platform: ipma

####################################################
#                                                  #
#                TRADFRI HUB                       #
#                                                  #
####################################################

tradfri:
  host: !secret tradfriHost
  #api_key: !secret tradfri_api_key
  allow_tradfri_groups: false

####################################################
#                                                  #
#                     MQTT                         #
#                                                  #
####################################################

mqtt:
  broker: !secret mqttBroker
  port: !secret mqttPort
  client_id: home-assistant-1

####################################################
#                                                  #
#                   XIAOMI                         #
#                                                  #
####################################################

xiaomi_aqara:
  discovery_retry: 10
  interface: !secret xiaomi_aqara_interface
  gateways:
    - mac: !secret xiaomi_aqara_gateways_1_mac
      host: !secret xiaomi_aqara_gateways_1_host
      key: !secret xiaomi_aqara_gateways_1_key

####################################################
#                                                  #
#                     TTS                          #
#                                                  #
####################################################

tts:
  - platform: google

####################################################
#                                                  #
#                 Custom Updater                   #
#                                                  #
####################################################

#custom_updater:
#  show_installable: true
#  hide_sensor: true
#  track:
#    - components
#    - cards
#    - python_scripts
#  card_urls:
#    #- https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
#    #- https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

####################################################
#                                                  #
#                    Notify                        #
#                                                  #
####################################################

notify:
  - name: hassiobot
    platform: slack
    api_key: !secret slack_oauth_access_token
    default_channel: '#general'
    username: hassiobot

####################################################
#                                                  #
#                  ChromeCast                      #
#                                                  #
####################################################

cast:
  media_player:
  - host: !secret chromecast_host

####################################################
#                                                  #
#                    Inputs                        #
#                                                  #
####################################################

input_boolean:
  living_room_heating_system:
    name: Heating system
    initial: off
    icon: mdi:radiator

input_number:
  living_room_heating_system_temperature:
    name: Heating system temperature
    initial: 23
    min: 20
    max: 30
    step: 1
    mode: box
    unit_of_measurement: '°C'
    icon: mdi:thermometer

wemo:
  discovery: false
  static:
    - 192.168.1.78

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################