####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

config:

frontend:
  javascript_version: latest

http:
  api_password: !secret api_password
  ip_ban_enabled: true
  login_attempts_threshold: 2

logger:
  default: error

history:
logbook:
sun:
map:

###################################### ##############
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

group: !include groups.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
media_player: !include media_players.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml

####################################################
#                                                  #
#                   WEATHER                        #
#                                                  #
####################################################

weather:
  - platform: ipma 

####################################################
#                                                  #
#                TRADFRI HUB                       #
#                                                  #
####################################################

tradfri:
  host: 192.168.1.96
  allow_tradfri_groups: false

####################################################
#                                                  #
#                     MQTT                         #
#                                                  #
####################################################

mqtt:
  broker: 192.168.1.20
  port: 1883
  client_id: home-assistant-1

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################

#camera:
#  - name: s8_cam
#    platform: generic
#    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.s8.attributes.latitude }},{{ states.device_tracker.s8.attributes.longitude }}&zoom=16&size=500x500&maptype=roadmap&markers=color:green%7Clabel:JA%7C{{ states.device_tracker.s8.attributes.latitude }},{{ states.device_tracker.s8.attributes.longitude }}
#    limit_refetch_to_url_change: true 