####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

# cloud:
#   google_actions:
#     filter:
#       include_domains:
#         - input_boolean
#         - script
#         - switch
#         - light
#         - media_player
#       exclude_entities:
# #        - media_player.lovelace_player_pc
#         - media_player.spotify
#     entity_config:
#       light.gateway_light_7c49eb193581:
#         room: Hall
#       light.sala:
#         room: Living Room
#       light.yeelight_color_bulb:
#         room: Living Room
#       input_boolean.living_room_heating_system:
#         room: Living Room
#       switch.d_link_smart_plug_w215:
#         room: Living Room
#       light.yeelight_color_bulb_2:
#         room: Kids Room
config:

frontend:
  javascript_version: latest

http:
  api_password: !secret api_password
  ip_ban_enabled: true
  login_attempts_threshold: 2
  base_url: hassio.duartebrito.pw
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.20

logger:
  default: error

system_health:
recorder:
history:
logbook:
sun:
map:
hassio:
lovelace:
#  mode: yaml

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

group: !include groups.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml
media_player: !include media_players.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml
light: !include light.yaml
camera: !include camera.yaml
scene: !include scene.yaml

####################################################
#                                                  #
#                   WEATHER                        #
#                                                  #
####################################################

weather:
  - platform: ipma

####################################################
#                                                  #
#                TRADFRI HUB                       #
#                                                  #
####################################################

tradfri:
  host: !secret tradfriHost
  allow_tradfri_groups: false

####################################################
#                                                  #
#                     MQTT                         #
#                                                  #
####################################################

mqtt:
  broker: !secret mqttBroker
  port: !secret mqttPort
  client_id: home-assistant-1

####################################################
#                                                  #
#                   XIAOMI                         #
#                                                  #
####################################################

xiaomi_aqara:
  discovery_retry: 10
  interface: !secret xiaomi_aqara_interface
  gateways:
    - mac: !secret xiaomi_aqara_gateways_1_mac
      host: !secret xiaomi_aqara_gateways_1_host
      key: !secret xiaomi_aqara_gateways_1_key

####################################################
#                                                  #
#                  ChromeCast                      #
#                                                  #
####################################################

cast:
  media_player:
  - host: !secret chromecast_host

####################################################
#                                                  #
#                    Inputs                        #
#                                                  #
####################################################

input_boolean:
  living_room_heating_system:
    name: Heating system
    initial: off
    icon: mdi:radiator

input_number:
  living_room_heating_system_temperature:
    name: Heating system temperature
    initial: 23
    min: 20
    max: 30
    step: 1
    mode: box
    unit_of_measurement: '°C'
    icon: mdi:thermometer

input_datetime:
  kids_room_start_time_motion_sensor:
    name: Start Time Motion Sensor
    has_date: false
    has_time: true
    initial: '08:00'
  kids_room_end_time_motion_sensor:
    name: End Time Motion Sensor
    has_date: false
    has_time: true
    initial: '23:00'

####################################################
#                                                  #
#                  Yeelight                        #
#                                                  #
####################################################

yeelight: !include yeelight.yaml

####################################################
#                                                  #
#               Google Assistant                   #
#                                                  #
####################################################

google_assistant:
  project_id: !secret project_id
  api_key: !secret api_key

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################