####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

config:

frontend:
  javascript_version: latest

http:
  api_password: !secret api_password
  ip_ban_enabled: true
  login_attempts_threshold: 2

logger:
  default: error

history:
logbook:
sun:
map:
hassio:

###################################### ##############
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

group: !include groups.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
media_player: !include media_players.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml

####################################################
#                                                  #
#                   WEATHER                        #
#                                                  #
####################################################

weather:
  - platform: ipma 

####################################################
#                                                  #
#                TRADFRI HUB                       #
#                                                  #
####################################################

tradfri:
  host: 192.168.1.96
  allow_tradfri_groups: false

####################################################
#                                                  #
#                     MQTT                         #
#                                                  #
####################################################

mqtt:
  broker: 192.168.1.20
  port: 1883
  client_id: home-assistant-1

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################

camera:
  - name: s8_cam
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.s8.attributes.latitude }},{{ states.device_tracker.s8.attributes.longitude }}&zoom=16&size=500x500&maptype=roadmap&format=png&visual_refresh=true&markers=size:small%7Ccolor:blue%7Clabel:%7CAS+MINHAS+CENAS&key=AIzaSyASLDNzi8IF6zG_4h1D1poLjMs30EpgC4k
    limit_refetch_to_url_change: true
  - name: s6_cam
    platform: generic
    still_image_url: https://api.mapbox.com/styles/v1/mapbox/streets-v9/static/pin-s-marker+285A98({{ states.device_tracker.s6.attributes.longitude }},{{ states.device_tracker.s6.attributes.latitude }})/{{ states.device_tracker.s6.attributes.longitude }},{{ states.device_tracker.s6.attributes.latitude }},16,0/500x500@2x?access_token=pk.eyJ1IjoiZHVhcnRlamJyaXRvIiwiYSI6ImNqbXZ0eXdqbDE0ZDgzd3F5YnozaTgxc3IifQ.ryTc2GBJkAhlyxnc7n4yWA&logo=false
    limit_refetch_to_url_change: true
  - name: j5_cam
    platform: generic
    still_image_url: https://api.mapbox.com/styles/v1/mapbox/streets-v9/static/pin-s-marker+285A98({{ states.device_tracker.j5.attributes.longitude }},{{ states.device_tracker.j5.attributes.latitude }})/{{ states.device_tracker.j5.attributes.longitude }},{{ states.device_tracker.j5.attributes.latitude }},16,0/500x500@2x?access_token=pk.eyJ1IjoiZHVhcnRlamJyaXRvIiwiYSI6ImNqbXZ0eXdqbDE0ZDgzd3F5YnozaTgxc3IifQ.ryTc2GBJkAhlyxnc7n4yWA&logo=false
    limit_refetch_to_url_change: true

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio-config.duartebrito.pw/

light:
  - platform: yeelight
    devices:
      192.168.1.156:
        name: Yeelight Color Bulb
        save_on_change: True
      192.168.1.157:
        name: Yeelight Color Bulb 2
        save_on_change: True