- alias: Movie Time
  sequence:
  - alias: ''
    data:
      brightness_pct: 20
      entity_id:
      - light.yeelight_color_bulb
      - light.sala
    service: light.turn_on

- alias: Turn on Lights Living Room
  sequence:
  - alias: ''
    data:
      brightness_pct: 100
      entity_id:
      - light.yeelight_color_bulb
      - light.sala
    service: light.turn_on

- alias: Turn off all Lights
  sequence:
  - alias: ''
    data:
      entity_id:
      - light.yeelight_color_bulb
      - light.yeelight_color_bulb_2
      - light.sala
    service: light.turn_off