resources:
  - type: module
    url: /local/mini-media-player/mini-media-player.js?v=0.8.9
  - type: module
    url: /local/mini-graph-card/mini-graph-card.js?v=0.0.8
  - type: js
    url: /local/slider-entity-row/slider-entity-row.js
  - type: js
    url: /local/text-element/text-element.js?v=0
  - type: js
    url: /local/state-attribute-element/state-attribute-element.js?v=0
  - type: js
    url: /local/lovelace-player/lovelace-player.js
  - type: js
    url: /local/lovelace-player/lovelace-player-config.js
  - type: js
    url: /local/monster-card/monster-card.js
  - type: js
    url: /local/plan-coordinates/plan-coordinates.js
title: SyTeR Home
views:
  - badges: []
    cards:
      - card:
          show_header_toggle: false
          title: Lights On
          type: entities
        filter:
          include:
            - domain: light
              state: 'on'
        show_empty: false
        type: 'custom:monster-card'
    icon: 'mdi:home-assistant'
    path: home
    title: Home
  - badges: []
    cards:
      - cards:
          - entities:
              - entity: light.gateway_light_7c49eb193581
                hide_when_off: true
                type: 'custom:slider-entity-row'
            show_header_toggle: false
            title: Lights
            type: entities
          - accuracy: 25
            color: '#3498db'
            entity: sensor.illumination_7c49eb193581
            font_size: 50
            height: 100
            hours_to_show: 24
            line_width: 4
            more_info: true
            type: 'custom:mini-graph-card'
        type: vertical-stack
      - entities:
          - binary_sensor.door_window_sensor_158d00028de42c
        show_header_toggle: false
        title: Sensors
        type: entities
      - cards:
          - color: '#3498db'
            detail: 2
            entity: sensor.temperature_158d00027897c8
            font_size: 50
            hours_to_show: 24
            line_width: 4
            more_info: true
            type: 'custom:mini-graph-card'
          - cards:
              - color: '#3498db'
                detail: 2
                entity: sensor.humidity_158d00027897c8
                font_size: 50
                hours_to_show: 24
                line_width: 4
                more_info: true
                type: 'custom:mini-graph-card'
              - color: '#3498db'
                detail: 2
                entity: sensor.pressure_158d00027897c8
                font_size: 50
                hours_to_show: 24
                icon: 'mdi:gauge'
                line_width: 4
                more_info: true
                type: 'custom:mini-graph-card'
            type: horizontal-stack
        type: vertical-stack
    path: hall
    title: Hall
  - badges: []
    cards:
      - entities:
          - entity: light.sala
            hide_when_off: true
            type: 'custom:slider-entity-row'
          - entity: light.yeelight_color_bulb
            hide_when_off: true
            type: 'custom:slider-entity-row'
        show_header_toggle: true
        title: Lights
        type: entities
      - entities:
          - input_boolean.living_room_heating_system
          - input_number.living_room_heating_system_temperature
          - type: divider
          - script.turn_on_low_lights_living_room
          - script.turn_on_medium_lights_living_room
          - script.turn_on_lights_living_room
          - script.turn_on_movie_time_lights_living_room
          - script.turn_off_lights_living_room
        show_header_toggle: false
        title: Controls
        type: entities
      - cards:
          - entities:
              - entity: switch.d_link_smart_plug_w215
              - entity: switch.aquarium
            show_header_toggle: false
            title: Switchs
            type: entities
          - entity: sensor.d_link_smart_plug_w215_temperature
            severity:
              green: 0
              red: 70
              yellow: 60
            title: Temperature
            type: gauge
        type: vertical-stack
      - cards:
          - color: '#3498db'
            detail: 2
            entity: sensor.temperature_158d0002786e71
            font_size: 50
            hours_to_show: 24
            line_width: 4
            more_info: true
            type: 'custom:mini-graph-card'
          - cards:
              - color: '#3498db'
                detail: 2
                entity: sensor.humidity_158d0002786e71
                font_size: 50
                hours_to_show: 24
                line_width: 4
                more_info: true
                type: 'custom:mini-graph-card'
              - color: '#3498db'
                detail: 2
                entity: sensor.pressure_158d0002786e71
                font_size: 50
                hours_to_show: 24
                icon: 'mdi:gauge'
                line_width: 4
                more_info: true
                type: 'custom:mini-graph-card'
            type: horizontal-stack
        type: vertical-stack
    path: living-room
    title: Living Room
  - badges: []
    cards:
      - cards:
          - entities:
              - entity: light.yeelight_color_bulb_2
                hide_when_off: true
                type: 'custom:slider-entity-row'
              - entity: binary_sensor.motion_sensor_158d00029a9d0e
            show_header_toggle: false
            title: Lights
            type: entities
          - accuracy: 25
            color: '#3498db'
            entity: sensor.illumination_158d00029a9d0e
            font_size: 50
            height: 100
            hours_to_show: 24
            line_width: 4
            more_info: true
            type: 'custom:mini-graph-card'
        type: vertical-stack
      - entities:
          - input_datetime.kids_room_start_time_motion_sensor
          - input_datetime.kids_room_end_time_motion_sensor
        show_header_toggle: false
        title: Controls
        type: entities
    path: kids-room
    title: Kids Room
  - badges: []
    cards:
      - cards:
          - entities:
              - device_tracker.duarte
              - sensor.duartebatterylevel
            show_header_toggle: false
            title: Duarte Phone Status
            type: entities
          - entities:
              - device_tracker.duarte
              - zone.home
              - zone.rita_school
              - zone.carolina_school
            type: map
        type: vertical-stack
      - cards:
          - entities:
              - device_tracker.silvia
              - sensor.silviabatterylevel
            show_header_toggle: false
            title: Silvia Phone Status
            type: entities
          - entities:
              - device_tracker.silvia
              - zone.home
              - zone.rita_school
              - zone.carolina_school
            type: map
        type: vertical-stack
      - cards:
          - entities:
              - device_tracker.beatriz
              - sensor.beatrizbatterylevel
            show_header_toggle: false
            title: Beatriz Phone Status
            type: entities
          - entities:
              - device_tracker.beatriz
              - zone.mom_home
            type: map
        type: vertical-stack
    icon: 'mdi:cellphone-android'
    path: phones-status
    title: Phones Status
  - badges: []
    cards:
      - card:
          show_header_toggle: false
          title: Automations
          type: entities
        filter:
          include:
            - domain: automation
        show_empty: true
        type: 'custom:monster-card'
      - card:
          show_header_toggle: false
          title: Scripts
          type: entities
        filter:
          include:
            - domain: script
        show_empty: true
        type: 'custom:monster-card'
      - entities:
          - sensor.tradfri_remote_control
          - sensor.motion_sensor_158d00029a9d0e_battery
          - sensor.door_window_sensor_158d00028de42c_battery
          - sensor.temperature_158d0002786e71_battery
          - sensor.temperature_158d00027897c8_battery
        show_header_toggle: false
        title: Batteries
        type: entities
    icon: 'mdi:home-automation'
    path: automation
    title: Automation
