
resources:
  - url: /local/mini-media-player/mini-media-player.js?v=0.8.9
    type: module
  - url: /local/mini-graph-card/mini-graph-card.js?v=0.0.8
    type: module
  - url: /local/slider-entity-row/slider-entity-row.js
    type: js
  - url: /local/text-element/text-element.js?v=0
    type: js
  - url: /local/state-attribute-element/state-attribute-element.js?v=0
    type: js
  - url: /local/lovelace-player/lovelace-player.js
    type: js
  - url: /local/lovelace-player/lovelace-player-config.js
    type: js
  - url: /local/monster-card/monster-card.js
    type: js
  - url: /local/plan-coordinates/plan-coordinates.js
    type: js

title: Home
views:
  - id: home
    title: Home
    icon: mdi:home-assistant
    cards:
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: Lights On
        filter:
          include:
            - domain: light
              state: 'on'
  - id: hall
    title: Hall
    cards:
      - id: hall-lights
        type: vertical-stack
        cards:
          - title: Lights
            type: entities
            show_header_toggle: false
            entities:
              - entity: light.gateway_light_7c49eb193581
                type: custom:slider-entity-row
                hide_when_off: true
          - entity: sensor.illumination_7c49eb193581
            type: "custom:mini-graph-card"
            height: 100
            line_width: 4
            font_size: 50
            color: '#3498db'
            more_info: true
            accuracy: 25
            hours_to_show: 24
      - id: hall-sensors
        title: Sensors
        type: entities
        entities:
          - binary_sensor.door_window_sensor_158d00028de42c
  - id: living-room
    title: Living Room
    cards:
      - id: living-room-tv
        type: media-control
        entity: media_player.samsung_tv_remote
      - id: living-room-lights
        title: Lights
        type: entities
        show_header_toggle: true
        entities:
          - entity: light.sala
            type: custom:slider-entity-row
            hide_when_off: true
          - entity: light.yeelight_color_bulb
            type: custom:slider-entity-row
            hide_when_off: true
      - id: living-room-controls
        title: Controls
        type: entities
        show_header_toggle: false
        entities:
          - input_boolean.living_room_heating_system
          - input_number.living_room_heating_system_temperature
          - type: divider
          - script.turn_on_low_lights_living_room
          - script.turn_on_medium_lights_living_room
          - script.turn_on_lights_living_room
          - script.turn_on_movie_time_lights_living_room
          - script.turn_off_lights_living_room
      - id: living-room-switchs
        type: vertical-stack
        cards:
          - title: Switchs
            type: entities
            show_header_toggle: false
            entities:
              - entity: switch.dlink_smart_plug_w215
          - title: Temperature
            type: gauge
            entity: sensor.dlink_smart_plug_w215_temperature
            severity:
              green: 0
              yellow: 60
              red: 70
      - id: living-room-sensors
        type: vertical-stack
        cards:
          - entity: sensor.temperature_158d0002786e71
            type: "custom:mini-graph-card"
            line_width: 4
            font_size: 50
            color: '#3498db'
            more_info: true
            hours_to_show: 24
            detail: 2
            labels: true
          - type: horizontal-stack
            cards:
              - entity: sensor.humidity_158d0002786e71
                type: "custom:mini-graph-card"
                line_width: 4
                font_size: 50
                color: '#3498db'
                more_info: true
                hours_to_show: 24
              - entity: sensor.pressure_158d0002786e71
                type: "custom:mini-graph-card"
                line_width: 4
                font_size: 50
                color: '#3498db'
                more_info: true
                hours_to_show: 24
                icon: mdi:gauge
      - id: living-room-sensors
        title: Sensors
        type: entities
        entities:
          - sensor.temperature_158d0002786e71
          - sensor.humidity_158d0002786e71
          - sensor.pressure_158d0002786e71
  - id: kids-room
    title: Kids Room
    cards:
      - id: kids-room-lights
        type: vertical-stack
        cards:
          - type: entities
            title: Lights
            show_header_toggle: false
            entities:
              - entity: light.yeelight_color_bulb_2
                type: custom:slider-entity-row
                hide_when_off: true
              - entity: binary_sensor.motion_sensor_158d00029a9d0e
          - entity: sensor.illumination_158d00029a9d0e
            type: "custom:mini-graph-card"
            height: 100
            line_width: 4
            font_size: 50
            color: '#3498db'
            more_info: true
            accuracy: 25
            hours_to_show: 24
  - id: media
    title: Media
    icon: mdi:play-network
    cards:
      - id: media-plex
        type: picture-elements
        image: /local/plex.jpg
        elements:
          - type: custom:text-element
            text: "<b style='color: orange; font-size: 18px'>Now Playing: </b>"
            style:
              top: 7%
              left: 15px
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: 'sessions'
            sub_attribute: 'title'
            suffix: ', '
            isMulti: true
            show_empty: false
            style:
              top: 20%
              left: 15px
              font-size: 16px
              color: white
              transform: none
          - type: custom:text-element
            text: "<b style='color: orange; font-size: 18px'>Statistics: </b>"
            style:
              top: 47%
              left: 15px
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: "top_movie"
            show_empty: true
            prefix: "<b style='color: orange; margin-right: 5px'>Most played movie: </b>"
            style:
              top: 60%
              left: 15px
              color: white
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: "top_tv_show"
            show_empty: true
            prefix: "<b style='color: orange; margin-right: 11px'>Most played show: </b>"
            style:
              top: 70%
              left: 15px
              color: white
              transform: none
          - type: custom:state-attribute-element
            entity: sensor.tautulli
            attribute: "top_user"
            show_empty: true
            prefix: "<b style='color: orange; margin-right: 20px'>Most active user: </b>"
            style:
              top: 80%
              left: 15px
              color: white
              transform: none
      - id: media-spotify
        type: custom:mini-media-player
        entity: media_player.spotify
        name: Spotify Player
        artwork: cover
        toggle_power: false
        power_color: true
        hide_volume: true
        show_progress: true
        show_source: true
      - id: media-chromecast
        type: custom:mini-media-player
        entity: media_player.chromecast_bedroom
  - id: weather
    title: Weather
    icon: mdi:weather-cloudy
    cards:
      - id: weather-ipma
        type: weather-forecast
        entity: weather.lisboa
      - id: weather-windy
        type: iframe
        url: https://embed.windy.com/embed2.html
        aspect_ratio: 80%
  - id: phones-status
    title: Phones Status
    icon: mdi:cellphone-android
    cards:
      - id: phones-status-duarte
        type: vertical-stack
        cards:
          - type: entities
            title: Duarte Phone Status
            show_header_toggle: true
            entities:
              - device_tracker.duarte
              - sensor.duartebatterylevel
          - type: map
            entities:
              - device_tracker.duarte
              - zone.home
              - zone.rita_school
              - zone.carolina_school
      - id: phones-status-silvia
        type: vertical-stack
        cards:
          - type: entities
            title: Silvia Phone Status
            show_header_toggle: true
            entities:
              - device_tracker.silvia
              - sensor.silviabatterylevel
          - type: map
            entities:
              - device_tracker.silvia
              - zone.home
              - zone.rita_school
              - zone.carolina_school
      - id: phones-status-beatriz
        type: vertical-stack
        cards:
          - type: entities
            title: Beatriz Phone Status
            show_header_toggle: true
            entities:
              - device_tracker.beatriz
              - sensor.beatrizbatterylevel
          - type: map
            entities:
              - device_tracker.beatriz
              - zone.mom_home
  - id: automation
    title: Automation
    icon: mdi:home-automation
    cards:
      - id: automation-automations-dyn
        type: custom:monster-card
        show_empty: true
        card:
          type: entities
          title: Automations
          show_header_toggle: false
        filter:
          include:
            - domain: automation
      - id: automation-scripts-dyn
        type: custom:monster-card
        show_empty: true
        card:
          type: entities
          title: Scripts
          show_header_toggle: false
        filter:
          include:
            - domain: script
      - id: automation-batteries
        type: entities
        title: Batteries
        show_header_toggle: true
        entities:
          - sensor.tradfri_remote_control
          - sensor.motion_sensor_158d00029a9d0e_battery
          - sensor.door_window_sensor_158d00028de42c_battery
          - sensor.temperature_158d0002786e71_battery
  - id: blueprint
    title: Blueprint
    icon: mdi:wrench
    panel: false
    cards:
      - type: vertical-stack
        cards:                  
          - type: picture-elements
            image: /local/floorplan/living-room-blueprint.png
            elements:
            - type: image
              tap_action: toggle
              entity: light.gateway_light_7c49eb193581
              image: /local/floorplan/living-room-celling-overlay.png
              state_filter:
                "unavailable": opacity(50%)
                "off": opacity(50%)
                "on": opacity(1%)
              style:
                width: 100%
                left: 50%
                top: 50%
            - type: image
              tap_action: toggle
              entity: light.sala
              image: /local/floorplan/living-room-floorlamp1-overlay.png
              state_filter:
                "unavailable": opacity(50%)
                "off": opacity(50%)
                "on": opacity(1%)
              style:
                width: 45.2%
                left: 78%
                top: 66.3%
            - type: image
              tap_action: toggle
              entity: light.yeelight_color_bulb
              image: /local/floorplan/living-room-floorlamp2-overlay.png
              state_filter:
                "unavailable": opacity(50%)
                "off": opacity(50%)
                "on": opacity(1%)
              style:
                width: 44.45%
                left: 22%
                top: 66%